// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StoreABC.Models;

public partial class Employee
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string City { get; set; }

    public int Age { get; set; }
}